apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ltpompz5n-python
  janus-idp.io/tekton: ltpompz5n-python
  backstage.io/kubernetes-id: ltpompz5n-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ltpompz5n-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
